### ISSUE TITLE
Scroll to Caret when active.

### ISSUE THREAD

**Issue by ctf0** [titoBouzout/BufferScroll#15]
the plugin had a very nice behavior which it used to scroll to the caret position when the file gets re-opened ,currently the caret position is remembered but the view doesn't scroll to that line number anymore.

**Comment by titoBouzout** [comment]
Can you reproduce the problem? Would you mind to add exact instructions. Thanks!

**Comment by ctf0** [comment]
u just open a file > scroll some line away from the viewport > put ur caret anywhere > close and open that file.

the file doesn't get scrolled but ur caret still at the same place u left it b4 u close, to jump to it,  just press up / down key.

**Comment by titoBouzout** [comment]
Look, I know something is malfunctioning, but without exact steps I cannot do anything. Im closing ok, I created a file, created text, scrolled to line 150, closed and opened and it works.

**Comment by titoBouzout** [comment]
Ok I got it, it does not work when the previous focused tab is an "untitled" tab. :)

**Comment by ctf0** [comment]
ah ,good catch ,thanx
