### ISSUE TITLE
Remember spell checking status

### ISSUE THREAD

**Issue by aziz** [titoBouzout/BufferScroll#17]
When ever I open a markdown file and enable spell checking I need to remember to re-enable spell checker. I think remembering spell checker can be part of BufferScroll since it's already saving all these other view specific settings and re-apply them on view load.

**Comment by titoBouzout** [comment]
Good idea, a list of settings to save and restore looks nice

**Comment by titoBouzout** [comment]
Thinking a little bit this may be good for the https://github.com/titobouzout/dictionaries package automatically turn on spell check for certain files! :)

**Comment by aziz** [comment]
I don't want to install that huge plugin, I don't need all those dictionaries. I just want the view to remember its spell checking state after close and reopen.

**Comment by titoBouzout** [comment]
Yes, I agree

**Comment by titoBouzout** [comment]
Hey done, now allows to remember a list of settings, with the new preference

	/* remembers the following view settings */
	"remember_settings_list": [
		"spell_check"
	],

**Comment by aziz** [comment]
:+1:
