### ISSUE TITLE
Sync Marks not working with other package

### ISSUE THREAD

**Issue by eorroe** [titoBouzout/BufferScroll#19]
`"synch_marks": true` does not work with [this package](https://packagecontrol.io/packages/MarkAndMove)

To use this package you might have to set up your own keybindings.

**Comment by titoBouzout** [comment]
It works, the purpose of "synch_marks" is to automatically adding the "mark" to any cloned view of the current focused one. Do you have steps to reproduce?

**Comment by eorroe** [comment]
I know what the purpose of `synch_marks` is. It works with normal marks but the other package uses multiple marks. Actually marks that are completely different than the default ones.

The default one is only one, while the ones from the package is multiple:

![Mark and move pic](https://packagecontrol.io/readmes/img/84dc47cd215cac4824f5ecb2ec107a3aff09eb96.gif)
