### ISSUE TITLE
Synced scrolling

### ISSUE THREAD

**Issue by cskiwi** [titoBouzout/BufferScroll#20]
Hi,

don't know if this is a feature or not, but couldn't figure it out if it was availible:

I have 2 files (translation files) and I would love to have both files always on the same scroll place, for easy editing multiple languages.

Can this be done?

**Comment by titoBouzout** [comment]
Looks like this package can do that: https://packagecontrol.io/packages/Sync%20View%20Scroll

This package sync the scroll differently, so you can view the same file in multiple panes. as shown in the picture https://camo.githubusercontent.com/842789a1d7559dbdbae75e1955abd8647ddd4a43/687474703a2f2f646c2e64726f70626f782e636f6d2f752f393330333534362f5375626c696d65546578742f42756666657253636f6c6c2f73796e632d7363726f6c6c2e706e67

**Comment by cskiwi** [comment]
Yep that did the trick!
thanks!
