### ISSUE TITLE
BufferScroll crashes ST3 when Cloning View

### ISSUE THREAD

**Issue by LeonardoGentile** [titoBouzout/BufferScroll#21]
I'm on Mac OS 10.9 and ST3 and this are my settings:
```
{
    "version": 7,
    "remember_color_scheme" : true,
    "synch_bookmarks" : false,
    "synch_folds" : false,
    "synch_marks" : true,
    "synch_scroll" : false,
   "restore_scroll": true,
    "typewriter_scrolling": false,
    "typewriter_scrolling_follow_cursor_movement": true,
    "use_animations": false,
    "i_use_cloned_views": true,
    "max_database_records": 500,
    "remember_settings_list": [
        "spell_check"
    ],
    "plain text": {
        "synch_scroll": false
    }
}
```

Whenever I select `File/New View Into File` I get a popup telling:
```
plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
```
The current file lose the syntax assignment so it is viewed as a simple text file. And if I bring up the command palette seems that `Package Control` is not there. I have to restart ST to bring the things back to normal. If I repeat this process I get the same result.
If I disable BufferScroll then I don't get any error.

This is what I see in the console. I've tried to disable also `CursorRuler` but the problem persists.
```
Traceback (most recent call last):
  File "CursorRuler in /Users/MyUser/Library/Application Support/Sublime Text 3/Installed Packages/CursorRuler.sublime-package", line 252, in on_command_mode_change
  File "CursorRuler in /Users/MyUser/Library/Application Support/Sublime Text 3/Installed Packages/CursorRuler.sublime-package", line 241, in on_selection_modified
  File "/Applications/Coding/Sublime Text 3.app/Contents/MacOS/sublime.py", line 166, in active_window
    return Window(sublime_api.active_window())
RuntimeError: maximum recursion depth exceeded
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
```

**Comment by titoBouzout** [comment]
CAn you please update to latest beta and let me know if the problem persists? Seems to me some work has been done in plugin_host

**Comment by titoBouzout** [comment]
OKei Im gonna close it

**Comment by LeonardoGentile** [comment]
Hi,
sorry couldn't do it before.
I've installed the latest version (couldn't find a beta branch) and now it seems to work :+1: 
I'll test a bit more and let you know if anything is wrong.

Thanks again

**Comment by titoBouzout** [comment]
Thanks to you for the report!

**Comment by LeonardoGentile** [comment]
sorry to tell you but today I started to get again random crashes while performing "New view into file" with a popup telling:
```plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted``` 
and the message in the console is: `RuntimeError: maximum recursion depth exceeded
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted`

Mac Os X Mavericks, ST3 Build 3083

**Comment by LeonardoGentile** [comment]
A possible hint: after the popup appears I can still use ST3 but it is very unstable and I have a weird behavior if I try to type in the file view that I had cloned (meaning I performed a "New view into file"). That is, if I type anything in the file for any button I type the syntax is lost (back to plain text) then after some milliseconds the syntax is recognized again so I get the colors that comes and go for each button I press

**Comment by titoBouzout** [comment]
think is fixed in latest version uploaded today, can you please try it? Thanks!

**Comment by LeonardoGentile** [comment]
Ok, I'll give it a try, thanks!
