### ISSUE TITLE
Plugin overrides the defualt syntax for a given extension

### ISSUE THREAD

**Issue by Gliptal** [titoBouzout/BufferScroll#22]
It seems that along with the wanted properties the current set syntax is also saved. This means that setting a new default syntax for a given extension will not work, since the new defualt will be immediately overwritten with the one saved by your plugin.

Steps to reproduce: 
- Open a file
- View > Syntax > Open all with current extension as...
- Select the desired new default syntax
- Open a different file with the same extension

The file will be opened with the previous syntax and not the new default one. You may also notice in the bottom right hand corner a brief change in the selected syntax when the plugin overrides your choice. If you disable the plugin and repeat the steps everything will work as expected, proving the issue.

Workarounds:
- Disable the plugin
- Manually set the new default syntax for every file

**Comment by titoBouzout** [comment]
I understand, this is now fixed in last commit , thanks for detailed report! :)

**Comment by Gliptal** [comment]
Blazing fast, thanks!
