### ISSUE TITLE
Buffer doesn't scroll horizontally

### ISSUE THREAD

**Issue by OmeGak** [titoBouzout/BufferScroll#24]
I use BufferScroll for the typewritter feature because I want to always have the cursor vertically centered on the buffer. For long lines, the expected behavior when word wrap is disabled is the buffer scrolling horizontally as I type or on cursor movement, but this doesn't happen when I have the following settings enabled:

````json
"typewriter_scrolling": true
"typewriter_scrolling_follow_cursor_movement": true
````

This is a quite bothersome problem to deal with, as I find myself either having to scroll manually with the mouse, disabling word wrap or simply disabling the typewriter feature.

**Comment by titoBouzout** [comment]
got it, thanks! :)

**Comment by OmeGak** [comment]
Thanks. Works like a charm.
