### ISSUE TITLE
Scroll doesn't follow cursor movement when selecting lines above

### ISSUE THREAD

**Issue by OmeGak** [titoBouzout/BufferScroll#25]
Another unexpected behavior I just noticed. When selecting text with `SHIFT` + :arrow_up: the scroll doesn't follow the cursor movement. Funnily, it follows it when text is selected pressing `SHIFT` + :arrow_down:.

**Comment by titoBouzout** [comment]
Nice catch again, I was using the selection end() which is the right most point in the selection. I should use point 2 of the selection, which is where the cursor is (bellow or above initial point)

**Comment by OmeGak** [comment]
:+1:
