### ISSUE TITLE
Folding doesn't work for nested code. How to enable?

### ISSUE THREAD

**Issue by wzup** [titoBouzout/BufferScroll#33]
I have collapsed nested code. And then collapsed an outer code. Then I have opened outer code, and nested code is not collapsed. How to enable the plugin to remember to keep nested code collapsed too?

Example:

```
// both are uncollapsed
>    a {
>         b {
               ...code is here...
           }
      }

// collapsed b
>    a {
^         b {...}
      }

// collapsed a
^   a {...}
```
So when I collapse `b` and then collapse `a` and then open `a` again, the `b` is not collapsed. Why? Need to enable

**Comment by DavidDono** [comment]
+1

**Comment by designedbyDC** [comment]
+1

**Comment by titoBouzout** [comment]
https://github.com/titoBouzout/BufferScroll/issues/13
