### ISSUE TITLE
Goto Definition & BufferScroll conflict

### ISSUE THREAD

**Issue by iamntz** [titoBouzout/BufferScroll#4]
So, it's me again. I just noticed an issue for last days and i wasn't sure what was about it.

Basically, a previous opened file will remember the scroll position, and on long files this will not act like it should. I have actually to `go to definition` twice: first to open the file, second to actually go to definition.

There is a way of detecting if open action was actually made dirrectly by the user or by the editor?

Thanks!

**Comment by titoBouzout** [comment]
I think this may now be finally ugly fixed? mmmmmmmh

**Comment by kaansoral** [comment]
interesting comments in the code :)
It's not yet picked by the package control, I will check it too when it updates through PC

**Comment by kaansoral** [comment]
I'm at v2015.01.09.23.21.56 / Mac OS X / ST3 - the buffer scroll still overrides goto_definition, is this expected?

**Comment by titoBouzout** [comment]
what has been fixed is the case of:
go to declaration from "CTRL+R"
go to definition when the quick panel is shown
double click in find and replace results

I'll look into go to definition when jumps directly.

**Comment by titoBouzout** [comment]
edit

**Comment by titoBouzout** [comment]
That last attempt to fix it has some kind of malfunctioning I still need to investigate, I'll take a look, sorry for messing scroll ^-^

**Comment by titoBouzout** [comment]
Guys, @q3xq3r @kaansoral @iamntz my previous fix was looking correct, but a typo make it behave incorrectly >.< Im sorry for that, I also included now support for the goto_definition, so in theory... now this package should finally ... (really?) behave correctly... can you please update, restart and well... test, I thank you so much, 

Kind regards

**Comment by kaansoral** [comment]
Works beautifully, thank you so much
(I haven't noticed any issues after some testing, I will let you know if there are any that arises later on, but I don't think so)

**Comment by ltWolfik** [comment]
I have similar problem - but i use "Go to definition" by CTags plugin. I need to use it twice, or use additionally ctrl+k,ctrl+c (set cursor to the center of screen). I set:
"synch_scroll": false 
but synchronization of scroll is still work and respectively i still have the problem. Can you please fix conflict between CTags and BufferScroll, or at least correct the turning off of synch_scroll.
Thanks in advance.

**Comment by titoBouzout** [comment]
synch_scroll is a different setting for syncing when you have the same file opened in many columns as shown in the picture https://camo.githubusercontent.com/842789a1d7559dbdbae75e1955abd8647ddd4a43/687474703a2f2f646c2e64726f70626f782e636f6d2f752f393330333534362f5375626c696d65546578742f42756666657253636f6c6c2f73796e632d7363726f6c6c2e706e67

**Comment by titoBouzout** [comment]
https://github.com/SublimeText/CTags/issues/280

**Comment by ltWolfik** [comment]
Sorry about synch_scroll.
Thanks for answer. I'm waiting for solution.

**Comment by ltWolfik** [comment]
Can you please create the capability to turn off restoring the scroll.
For awhile there is conflict with CTags, I would like to use it for the rest: restoring cursor positions, also the selections, marks, bookmarks, foldings ...

**Comment by titoBouzout** [comment]
For sure, why not =), this is done in last commit. i didn't test...  :P Please let me know, thanks

**Comment by ltWolfik** [comment]
It works correctly. Thank you for responsiveness and help!

**Comment by titoBouzout** [comment]
You are welcome

**Comment by titoBouzout** [comment]
I consider it closed :) AMAZING
