### ISSUE TITLE
Large Database file causes slow on_deactivated callback

### ISSUE THREAD

**Issue by forivall** [titoBouzout/BufferScroll#8]
I recently had to track down that this plugin was making ST2 slow, because I had a large history of files. Ideally, the history should be pruned every once in awhile, or be kept at a maximum number of files.

My database file was 246KB gzipped, 787KB unzipped.

Current workaround is to remove the old database, but that loses all history.

**Comment by q3xq3r** [comment]
Here's what I came up with:
pull request #14 'limit database size using OrderedDict'

**Comment by titoBouzout** [comment]
A patch has been merged, so I guess this is no longer a problem. Thanks
